apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: mypf
spec:
  selector:
    matchLabels:
      app: mypf
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: mypf
    spec:
      containers:
        - name: mypf
          image: vinayakpadukone/mypfapp # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 80 # The port that the container is running on in the cluster
